name: Cloud Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/cloud-user.pem
          chmod 600 ~/.ssh/cloud-user.pem

      - name: Deploy HTML to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/cloud-user.pem" \
          app/index.html ubuntu@${{ secrets.EC2_IP }}:/var/www/html/index.html
