name: Deploy HTML to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/cloud-user.pem
          chmod 600 ~/.ssh/cloud-user.pem
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy HTML to EC2
        run: |
          rsync -avz -e "ssh -i ~/.ssh/cloud-user.pem" app/index.html ubuntu@${{ secrets.EC2_IP }}:/var/www/html/index.html

      - name: Reload nginx
        run: |
          ssh -i ~/.ssh/cloud-user.pem ubuntu@${{ secrets.EC2_IP }} "sudo systemctl reload nginx"
